FIX : Update required dependency ----------------------------------------------
* I have added two dependancies:
** django
** django-core

* This is due to the fact that after installing wagtail only and trying to start the project with `wagtail start mysite` you will get the following error:
```
Traceback (most recent call last):
File "/home/vagrant/wagdev/ve/bin/wagtail", line 7, in <module>
from wagtail.bin.wagtail import main
File "/home/vagrant/wagdev/ve/local/lib/python2.7/site-packages/wagtail/bin/wagtail.py", line 7, in <module>
from django.core.management import ManagementUtility
ImportError: No module named django.core.management
```

django-core on its own does not solve this and thus why django has been included here.
It may be better to have this in a dependency file but I though this may be a good first step.