Support rich text rewrite handlers with custom pks
The Wagtail documentation describes the supported approach for defining
custom rich text rewrite handlers, by inheriting from LinkHandler or
EmbedHandler [0]. This doesn't work using the default
`EntityHandler.get_instance` if the entity model class uses a custom
primary key (not `id`).

The default instance retrival code is here [1]. Note that it does a
`get(id=attrs['id'])`, which fails with an error like the following if
there is no `id` field on the model class:

> django.core.exceptions.FieldError: Cannot resolve keyword 'id' into
field. Choices are: ...

If this code instead used the Django `pk` lookup shortcut, it could
automatically query against the model's primary key, whatever it happens
to be named [2].

This commit makes that change, adds a regression test that verifies
the desired behavior, and updates the docs accordingly.

[0] https://docs.wagtail.io/en/v2.7/advanced_topics/customisation/rich_text_internals.html#rewrite-handlers
[1] https://github.com/wagtail/wagtail/blob/c72a4e09413bc6fc3a9cac8ed173378aa8652925/wagtail/core/rich_text/__init__.py#L77
[2] https://docs.djangoproject.com/en/3.0/topics/db/queries/#the-pk-lookup-shortcut